// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: algorithm.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_algorithm_2eproto__INCLUDED
#define GRPC_algorithm_2eproto__INCLUDED

#include "algorithm.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace algorithm {

class Algorithm final {
 public:
  static constexpr char const* service_full_name() {
    return "algorithm.Algorithm";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::algorithm::AlgorithmReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>> AsyncInitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>>(AsyncInitModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>> PrepareAsyncInitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>>(PrepareAsyncInitModelRaw(context, request, cq));
    }
    virtual ::grpc::Status ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::algorithm::AlgorithmReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>> AsyncReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>>(AsyncReleaseModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>> PrepareAsyncReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>>(PrepareAsyncReleaseModelRaw(context, request, cq));
    }
    virtual ::grpc::Status Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::algorithm::InferenceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>> AsyncInference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>>(AsyncInferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>> PrepareAsyncInference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>>(PrepareAsyncInferenceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>* AsyncInitModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>* PrepareAsyncInitModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>* AsyncReleaseModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::AlgorithmReply>* PrepareAsyncReleaseModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>* AsyncInferenceRaw(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::algorithm::InferenceReply>* PrepareAsyncInferenceRaw(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::algorithm::AlgorithmReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>> AsyncInitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>>(AsyncInitModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>> PrepareAsyncInitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>>(PrepareAsyncInitModelRaw(context, request, cq));
    }
    ::grpc::Status ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::algorithm::AlgorithmReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>> AsyncReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>>(AsyncReleaseModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>> PrepareAsyncReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>>(PrepareAsyncReleaseModelRaw(context, request, cq));
    }
    ::grpc::Status Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::algorithm::InferenceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>> AsyncInference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>>(AsyncInferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>> PrepareAsyncInference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>>(PrepareAsyncInferenceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, std::function<void(::grpc::Status)>) override;
      void InitModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, std::function<void(::grpc::Status)>) override;
      void ReleaseModel(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response, std::function<void(::grpc::Status)>) override;
      void Inference(::grpc::ClientContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>* AsyncInitModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>* PrepareAsyncInitModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>* AsyncReleaseModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::algorithm::AlgorithmReply>* PrepareAsyncReleaseModelRaw(::grpc::ClientContext* context, const ::algorithm::AlgorithmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>* AsyncInferenceRaw(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::algorithm::InferenceReply>* PrepareAsyncInferenceRaw(::grpc::ClientContext* context, const ::algorithm::InferenceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_InitModel_;
    const ::grpc::internal::RpcMethod rpcmethod_ReleaseModel_;
    const ::grpc::internal::RpcMethod rpcmethod_Inference_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status InitModel(::grpc::ServerContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response);
    virtual ::grpc::Status ReleaseModel(::grpc::ServerContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response);
    virtual ::grpc::Status Inference(::grpc::ServerContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InitModel() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitModel(::grpc::ServerContext* context, ::algorithm::AlgorithmRequest* request, ::grpc::ServerAsyncResponseWriter< ::algorithm::AlgorithmReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseModel(::grpc::ServerContext* context, ::algorithm::AlgorithmRequest* request, ::grpc::ServerAsyncResponseWriter< ::algorithm::AlgorithmReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Inference() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInference(::grpc::ServerContext* context, ::algorithm::InferenceRequest* request, ::grpc::ServerAsyncResponseWriter< ::algorithm::InferenceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_InitModel<WithAsyncMethod_ReleaseModel<WithAsyncMethod_Inference<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InitModel() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response) { return this->InitModel(context, request, response); }));}
    void SetMessageAllocatorFor_InitModel(
        ::grpc::MessageAllocator< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitModel(
      ::grpc::CallbackServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::algorithm::AlgorithmRequest* request, ::algorithm::AlgorithmReply* response) { return this->ReleaseModel(context, request, response); }));}
    void SetMessageAllocatorFor_ReleaseModel(
        ::grpc::MessageAllocator< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseModel(
      ::grpc::CallbackServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Inference() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::algorithm::InferenceRequest, ::algorithm::InferenceReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::algorithm::InferenceRequest* request, ::algorithm::InferenceReply* response) { return this->Inference(context, request, response); }));}
    void SetMessageAllocatorFor_Inference(
        ::grpc::MessageAllocator< ::algorithm::InferenceRequest, ::algorithm::InferenceReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::algorithm::InferenceRequest, ::algorithm::InferenceReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Inference(
      ::grpc::CallbackServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_InitModel<WithCallbackMethod_ReleaseModel<WithCallbackMethod_Inference<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InitModel() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Inference() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InitModel() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Inference() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInference(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InitModel() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InitModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReleaseModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Inference() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Inference(context, request, response); }));
    }
    ~WithRawCallbackMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Inference(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InitModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InitModel() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>* streamer) {
                       return this->StreamedInitModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InitModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InitModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInitModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::algorithm::AlgorithmRequest,::algorithm::AlgorithmReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReleaseModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReleaseModel() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::algorithm::AlgorithmRequest, ::algorithm::AlgorithmReply>* streamer) {
                       return this->StreamedReleaseModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReleaseModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReleaseModel(::grpc::ServerContext* /*context*/, const ::algorithm::AlgorithmRequest* /*request*/, ::algorithm::AlgorithmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReleaseModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::algorithm::AlgorithmRequest,::algorithm::AlgorithmReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Inference() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::algorithm::InferenceRequest, ::algorithm::InferenceReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::algorithm::InferenceRequest, ::algorithm::InferenceReply>* streamer) {
                       return this->StreamedInference(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Inference(::grpc::ServerContext* /*context*/, const ::algorithm::InferenceRequest* /*request*/, ::algorithm::InferenceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInference(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::algorithm::InferenceRequest,::algorithm::InferenceReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_InitModel<WithStreamedUnaryMethod_ReleaseModel<WithStreamedUnaryMethod_Inference<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_InitModel<WithStreamedUnaryMethod_ReleaseModel<WithStreamedUnaryMethod_Inference<Service > > > StreamedService;
};

}  // namespace algorithm


#endif  // GRPC_algorithm_2eproto__INCLUDED
